services:  
  kafka_producer:
      build:
        context: ./producer
      container_name: kafka_producer
      command: ["python", "scheduler.py"]
      environment:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
        TOPIC_SCAN: ${TOPIC_SCAN}
        TOPIC_FULL: ${TOPIC_FULL}
        TOPIC_CHECK_PORT: ${TOPIC_CHECK_PORT}
      volumes:
        - ./producer/schedule_config.json:/app/schedule_config.json:ro
