services:
  scan_ip:
    build:
      context: .
    container_name: scan_ip
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      TOPIC_SCAN: ${TOPIC_SCAN}
      TOPIC_SCAN_RESULT: ${TOPIC_SCAN_RESULT}
    volumes:
      - ./scan_ip/schedule_config.json:/app/schedule_config.json:ro
